.changeset/four-pears-divide.md, packages/core/package.json, packages/nextjs/package.json
without this, types were not picked up for me when `tsconfig.json#moduleResolution` was set to `nodenext`.
=> fix: add types to package.json#exports

docs/src/components/mdx/code-block.tsx, docs/src/styles/globals.css
The 'copy to clipboard' button shown in code blocks shows overlapping icons when `copied` is `true`.
This is because [Rehype Pretty Code](https://rehype-pretty-code.netlify.app) renders the `<pre>` element twice when both a `light` and `dark` theme have been configured. Since this project appends the 'copy to clipboard' button to `<pre>`, two are rendered for each code block.
**The solution:**
- Add `data-theme` to each 'copy to clipboard' button (and to the language icon for good measure)
- Hide all elements where `[data-theme="not the current theme"]`
- Remove the unnecessary `p-1` on the `CheckCheck` icon
This PR also changes the button from a `<div>` to an actual `<button>` with an `aria-label`
**Before:**
https://user-images.githubusercontent.com/13686180/235287268-ecddd5fe-3104-4602- …
=> docs: fix overlapping copy to clipboard button

.changeset/thin-bats-relax.md, docs/src/components/mdx/code-block.tsx, docs/src/styles/globals.css
Fix #34 
Fixed codeblock overlapping icon caused by the recent fix from #32. 
As the CSS fix from #32 (shown below), will always apply to element that has `data-theme`.
```css
[data-theme="light"] {
@apply block dark:hidden;
}
[data-theme="dark"] {
@apply hidden dark:block;
}
``` 
However, the language icon works slightly different, where the icon will only show if the title is present. So, the solution is to handle the hide/show separately.
=> Codeblock language icon fix

.changeset/sour-laws-allow.md, packages/core/index.ts
If we try to use this package in Vite (SPA) project, it will throw an error `Uncaught ReferenceError: process is not defined` on client-side, as Vite is using `import.meta.env` instead of `process.env`. 
So, the fix is to remove all the existing `process.env` usage.
> Note that Astro is an exception, as most of the code are run/build in Node runtime, which the `process.env` is always available.
=> Remove `process.env` usage from the core

docs/src/app/docs/nextjs/page.mdx
I was playing around with this lit library today but wasted a few minutes trying to understand what `~/env` meant. I thought it generated type definition files but couldn't get typescript to compile. I updated docs to use `~/env.mjs` instead of `~/env` so people don't get confused thinking like me.
=> chore: next.js example in docs

docs/src/app/docs/nuxt/page.mdx
The nuxt examples in the docs are importing code from the nextjs env package, while they should import the nuxtjs env package.
=> docs: fix typo

docs/src/app/docs/recipes/page.mdx
Zod has a "new" and more concise api for making type coercions for primitives.
I believe it's better then the actual recipe present in the docs, specially for numbers. But it's also nice to keep the current recipe in the docs because it's a more manual way of doing it and may be useful to someone.
```ts
z.string()
.transform((s) => parseInt(s, 10))
.pipe(z.number()),
```
```ts
z.coerce.number()
```
=> docs: add zod primitives coercion recipes

docs/next.config.mjs, docs/src/app/docs/layout.tsx, docs/src/app/layout.tsx, docs/src/app/page.tsx, docs/src/components/main-nav.tsx, docs/src/components/mobile-nav.tsx, docs/src/components/site-header.tsx, docs/src/components/theme-toggle.tsx, docs/src/components/ui/button.tsx, docs/src/styles/globals.css, docs/tailwind.config.ts
I have changed the docs site to make it more accessible and improve SEO. I also fixed the issue where the main navigation links were not showing in their active state. Here are the details of the changes we made:
- Added active states to main navigation links using [`useSelectedLayoutSegment()`](https://nextjs.org/docs/app/api-reference/functions/use-selected-layout-segment)
```ts
function isActive(href: string) {
const segment = useSelectedLayoutSegment();
if (!segment) return false;
return href.startsWith(`/${segment}`);
}
```
- Changed muted colors a little to improve contrast ratio and gave buttons accessible names, increasing accessibility scores on the homepage from **85** to **100**
- Added `hoverOnlyWhenSupported`, which will prevent any hover styles from being shipped to devices …
=> Improved accessibility and Fixed main nav active states 

.changeset/nervous-houses-cover.md, .gitignore, examples/astro/src/env.d.ts, packages/core/index.ts, packages/core/test/smoke.test.ts, packages/nextjs/test/smoke.test.ts
=> feat: env vars should be readonly

packages/core/index.ts
=> fix: cjs __esModule field should not be evaluated as env variable

docs/mdx-components.tsx, docs/src/components/icons.tsx
Links like https://env.t3.gg/docs/customization#skipping-validation will now scroll to the appropriate heading. Added anchor tags to each heading level, so you can easily share links to them . Heading ID's are generated by basic slugify function.
Added an underline on hover to let users know you can click on them. 
Closes my own issue, #115
=> Docs: Add anchor # links to headings

docs/src/app/docs/recipes/page.mdx
As discussed in #143 this removes a misleading / faulty example from the coercion recipes regarding booleans.
Related Zod Issue: https://github.com/colinhacks/zod/issues/1630
Maybe it could also be useful to add a reference to that issue in the docs ¯\\\_(ツ)\_/¯
=> docs: remove misleading boolean coercion example from recipes

docs/src/app/docs/nextjs/page.mdx
This page appears to have `<Callout />`s included that reference an older version of the docs, where the instructions for next.js were based on using `@t3-oss/env-core`.
=> Update next.js docs page to be more clear

docs/src/app/docs/nextjs/page.mdx
According to https://github.com/nodejs/node/issues/37845, `new URL(import.meta.url).pathname` can not get the correct file path on Windows.
=> docs: use fileURLToPath to get correct file path on windows

docs/src/app/docs/nuxt/page.mdx
- This option `runtimeEnv` is omitted because it's set to `process.env` by default for nuxt.
- This package now requires typescript >=5
=> docs: remove `runtimeEnv` option from examples for nuxt

packages/core/src/index.ts
@juliusmarminge We hit the faulty server detection explained in #154 when using t3-env on Netlify in a middleware in Next.js. Netlify uses Deno to bundle for edge, and this resulted in builds failing with "❌ Attempted to access a server-side environment variable on the client".
I think Netlify + Next.js middleware + t3-env qualifies as "_common_ setups widely used" as you put it in [your comment](https://github.com/t3-oss/t3-env/issues/154#issuecomment-2016830936)
We would appreciate out of the box support for this combo.
=> fix: identify Deno as server (#154)

.changeset/polite-fireants-drive.md, packages/core/src/index.ts, packages/nextjs/src/index.ts, packages/nuxt/src/index.ts
This creates a `CreateEnv` utility type in `core/index.ts`. This type is then used to provide an explicit return type for the framework-specific `createEnv` calls. This would have prevented the Zod 3.23.0 declaration issue.
=> Add explicit return types

docs/src/app/docs/core/page.mdx, docs/src/app/docs/nextjs/page.mdx
- updates the docs from TS peer dep v4 -> v5
- npm currently shows v5 as the minimum peer dep
```
pnpm view @t3-oss/env-nextjs peerDependencies
{ typescript: '>=5.0.0', zod: '^3.0.0' }
pnpm view @t3-oss/env-core peerDependencies
{ typescript: '>=5.0.0', zod: '^3.0.0' }
```
=> fix(docs): update TS version for peer dependency

docs/src/app/docs/nextjs/page.mdx
Updated the Next.js docs code snippets when separating environment variables between environments, since:
- The server had a wrong implementation of `runtimeEnv` that needs to be manually specified, using `experimental__runtimeEnv` instead if just referencing `process.env` (with comments)
- The client was missing the proper `NEXT_PUBLIC` prefix on the variable and the manual mapping of definition to `process.env` variable, since the client enforces these regardless of the Next.js version.
=> Update Next.js example code snippets

.changeset/shiny-frogs-sneeze.md, docs/src/app/docs/customization/page.mdx, packages/core/src/presets.ts
ref: https://docs.render.com/environment-variables#all-runtimes
=> feat(core): add render preset

.changeset/giant-kids-promise.md, docs/src/app/docs/customization/page.mdx, packages/core/src/presets.ts
See: https://fly.io/docs/machines/runtime-environment/#environment-variables
=> feat: add fly.io preset

docs/src/app/docs/nextjs/page.mdx
I ran into some odd issues when using jiti 2+, I think it may save a lot of heartache and needless GH issues to mention that it should use v1+
=> Add version disclaimer to jiti docs

docs/src/app/docs/nextjs/page.mdx
- Add help for nextjs standalone output.
=> docs(nextjs): add config for standalone output

bun.lock, packages/core/package.json, packages/nextjs/package.json, packages/nuxt/package.json
When it tried to install `@t3-oss/env-core` with pnpm i was surprised to see pnpm install `arktype` as a dependency. The core package should list `asktype` as an optional dependency since it work with any standard schema compatible library and let the user install his favorite validation library.
=> fix: arktype not properly listed as an optional peer dependencies
